apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-san-eco-vp-secret
type: Opaque
stringData:
  username: cluster-admin
  password: password
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san-eco-vp
spec:
  version: 1
  storageDriverName: ontap-san-economy
  managementLIF: 10.0.0.1
  dataLIF: 10.0.0.2
  svm: trident_svm_eco
  credentials: 
    name: backend-tbc-ontap-san-eco-vp-secret
  defaults:
    spaceAllocation: 'false'
    encryption: 'false'
  labels:
    store: san_economy_store
  region: us_east_1
  storage:
  - labels:
      app: oracledb
      cost: '30'
    zone: us_east_1a
    defaults:
      spaceAllocation: 'true'
      encryption: 'true'
  - labels:
      app: postgresdb
      cost: '20'
    zone: us_east_1b
    defaults:
      spaceAllocation: 'false'
      encryption: 'true'
  - labels:
      app: mysqldb
      cost: '10'
    zone: us_east_1c
    defaults:
      spaceAllocation: 'true'
      encryption: 'false'
