apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: basic
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: basic
