kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: full
  annotations:
    trident.netapp.io/exportPolicy: "default"
    trident.netapp.io/snapshotPolicy: "default-1weekly"
    trident.netapp.io/protocol: "file"
    trident.netapp.io/snapshotDirectory: "false"
    trident.netapp.io/unixPermissions: "---rwxrwxrwx"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: silver
