apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bronze
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "solidfire_10.0.0.1:Bronze"
  fsType: "ext4"
