apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-san-virtual-pools-secret
type: Opaque
stringData:
  username: cluster-admin
  password: password
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san-virtual-pools
spec:
  version: 1
  storageDriverName: ontap-san
  managementLIF: 10.0.0.1
  dataLIF: 10.0.0.2
  svm: trident_svm
  credentials: 
    name: backend-tbc-ontap-san-virtual-pools-secret
  defaults:
    spaceAllocation: 'false'
    encryption: 'false'
  labels:
    store: san_store
  region: us_east_1
  storage:
  - labels:
      protection: gold
      points: '40000'
    zone: us_east_1a
    defaults:
      spaceAllocation: 'true'
      encryption: 'true'
  - labels:
      protection: silver
      points: '20000'
    zone: us_east_1b
    defaults:
      spaceAllocation: 'false'
      encryption: 'true'
  - labels:
      protection: bronze
      points: '5000'
    zone: us_east_1c
    defaults:
      spaceAllocation: 'true'
      encryption: 'false'
